const getters = {
  sidebar: state => state.app.sidebar,
  language: state => state.app.language,
  size: state => state.app.size,
  device: state => state.app.device,
  visitedViews: state => state.tagsView.visitedViews,
  cachedViews: state => state.tagsView.cachedViews,
  token: state => state.user.token,
  avatar: state => state.user.avatar,
  name: state => state.user.name,
  introduction: state => state.user.introduction,
  roles: state => state.user.roles,
  permission_routes: state => state.permission.routes,
  meunList: state => state.permission.meunList,
  leftMeunList: state => state.permission.leftMeunList,
  rightMoreMeunList: state => state.permission.rightMoreMeunList,
  topOffsetWidth: state => state.permission.topOffsetWidth,
  authentionList: state => state.permission.authentionList,
  adminUser: state => state.permission.adminUser,
  logoData: state => state.permission.logoData,
  errorLogs: state => state.errorLog.logs,
}
export default getters
