/**
 * 营销活动类型元数据与字段可见性配置
 */
export const ACTIVITY_TYPES = [
  {
    value: '1',
    label: '注册领取',
    tag: '新客拉新',
    icon: 'el-icon-user-solid',
    color: '#30B08F',
    colorLight: '#6ee7b7',
    description: '用户注册成功后自动发放卡券，降低新客首充门槛、提升转化。',
    viewPermission: ':marketing:activity:register:view',
    editPermission: ':marketing:activity:register:edit',
    platformOnly: true,
    drawerForm: true,
    showRewardThreshold: false,
    showStationScope: false,
    showUserScope: true,
    userScopeInSub: false,
    subFields: [],
    autoIssueTip: '用户通过手机号完成注册后自动发放卡券。'
  },
  {
    value: '2',
    label: '充值领取',
    tag: '提升客单价',
    icon: 'el-icon-wallet',
    color: '#22c55e',
    colorLight: '#86efac',
    description: '用户充值满指定金额后赠送卡券，激励预付费、提高资金沉淀。',
    viewPermission: ':marketing:activity:recharge:view',
    editPermission: ':marketing:activity:recharge:edit',
    platformOnly: true,
    drawerForm: true,
    showRewardThreshold: true,
    showStationScope: false,
    showUserScope: true,
    userScopeInSub: false,
    subFields: ['limitType', 'limitCount'],
    autoIssueTip: '用户余额充值成功后，按最高匹配档位自动发放卡券。'
  },
  {
    value: '3',
    label: '定向发放',
    tag: '精准触达',
    icon: 'el-icon-s-promotion',
    color: '#16a34a',
    colorLight: '#4ade80',
    description: '向指定客户、用户分组或用户定向推送卡券，适合召回与 VIP 运营。',
    viewPermission: ':marketing:activity:directional:view',
    editPermission: ':marketing:activity:directional:edit',
    drawerForm: true,
    showRewardThreshold: false,
    showStationScope: false,
    showUserScope: true,
    userScopeInSub: true,
    subFields: ['sendType', 'sendTime', 'userScope']
  },
  {
    value: '4',
    label: '充电领取',
    tag: '提升充电量',
    icon: 'el-icon-lightning',
    color: '#059669',
    colorLight: '#34d399',
    description: '用户充电满指定度数后可领取奖励，激励用户多充多领。',
    viewPermission: ':marketing:activity:charge:view',
    editPermission: ':marketing:activity:charge:edit',
    drawerForm: true,
    showRewardThreshold: false,
    showStationScope: true,
    showUserScope: true,
    userScopeInSub: true,
    subFields: ['limitPower', 'limitType', 'limitCount', 'stationScope', 'chargeUserScope'],
    autoIssueTip: '汽车充电结算后，活动期内累计充电度数达标自动发放卡券。'
  },
  {
    value: '5',
    label: '扫码领取',
    tag: '线下引流',
    icon: 'el-icon-full-screen',
    color: '#0d9488',
    colorLight: '#5eead4',
    description: '用户扫描活动二维码即可领券，适合地推、站点物料与线下活动。',
    viewPermission: ':marketing:activity:scan:view',
    editPermission: ':marketing:activity:scan:edit',
    drawerForm: true,
    showRewardThreshold: false,
    showStationScope: false,
    showUserScope: true,
    userScopeInSub: true,
    subFields: ['activityTitle', 'activityImage', 'limitType', 'limitCount', 'scanUserScope']
  },
  {
    value: '6',
    label: '券码兑换',
    tag: '渠道分发',
    icon: 'el-icon-tickets',
    color: '#10b981',
    colorLight: '#6ee7b7',
    description: '生成兑换码分发给用户，输入码即可兑换卡券，便于合作渠道投放。',
    viewPermission: ':marketing:activity:exchange:view',
    editPermission: ':marketing:activity:exchange:edit',
    drawerForm: true,
    showRewardThreshold: false,
    showStationScope: false,
    showUserScope: true,
    userScopeInSub: true,
    subFields: ['sendTotalCount', 'exchangeUserScope']
  },
  {
    value: '7',
    label: '电站折扣',
    tag: '电站促销',
    icon: 'el-icon-office-building',
    color: '#2563eb',
    colorLight: '#93c5fd',
    description: '按电站配置电费/服务费折扣或固定价，支持分电站费率、使用星期与时段控制。',
    viewPermission: ':marketing:activity:stationDiscount:view',
    editPermission: ':marketing:activity:stationDiscount:edit',
    drawerForm: true,
    isDiscount: true,
    showRewardThreshold: false,
    showStationScope: false,
    showUserScope: false,
    userScopeInSub: false,
    subFields: []
  },
  {
    value: '8',
    label: '用户折扣',
    tag: '精准优惠',
    icon: 'el-icon-user',
    color: '#7c3aed',
    colorLight: '#c4b5fd',
    description: '向指定用户分组或用户配置充电折扣/固定价，限定可用电站与生效时段。',
    viewPermission: ':marketing:activity:userDiscount:view',
    editPermission: ':marketing:activity:userDiscount:edit',
    drawerForm: true,
    isDiscount: true,
    showRewardThreshold: false,
    showStationScope: false,
    showUserScope: false,
    userScopeInSub: false,
    subFields: []
  }
]

export function getActivityTypeMeta(type) {
  return ACTIVITY_TYPES.find(item => item.value === String(type)) || null
}

export const ACTIVITY_STATUS = [
  { value: '1', label: '进行中', tagType: 'success' },
  { value: '2', label: '未开始', tagType: 'warning' },
  { value: '3', label: '已停用', tagType: 'danger' },
  { value: '4', label: '已到期', tagType: 'info' },
  { value: '5', label: '卡券不足', tagType: 'danger' },
  { value: '6', label: '卡券失效', tagType: 'danger' }
]
